import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
!pip install alpha-vantage
from alpha-vantage.timeseries import TimeSeries
demo = 'HK550L4D3IIB0IMZ' #YOUR API KEY HERE
#overall american market
print("overall american market stock AAPL")
alpha1 = pd.read_csv('https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=AAPL&apikey=' + demo + '&datatype=csv')
alpha1.head()
alpha1.head(10)
alpha1.set_index('timestamp', inplace = True)
alpha1.head(10)
list = alpha1.index.tolist()
list[0:20]
alpha1[['open', 'close']].head(20).plot(figsize = (10,7))
plt.xticks(rotation = 45)
plt.show()
alpha1.iloc[:, 0:2].plot()
plt.show()
ts = TimeSeries(key = 'HK550L4D3IIB0IMZ', output_format='pandas')
print("overall canadian market stock TSX")
alpha2 = pd.read_csv('https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=TSX&apikey=' + demo + '&datatype=csv')
alpha2.head()
alpha2.set_index('timestamp', inplace = True)
alpha2.head(10)
list = alpha2.index.tolist()
list[0:20]
alpha2[['open', 'close']].head(20).plot(figsize = (10,7))
plt.xticks(rotation = 45)
plt.show()
alpha2.iloc[:, 0:2].plot()
plt.show()
ts = TimeSeries(key = 'HK550L4D3IIB0IMZ', output_format='pandas')
print("TRAVEL SECTOR STOCK MARKET LUV")
alpha3 = pd.read_csv('https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=LUV&apikey=' + demo + '&datatype=csv')
alpha3.head()
alpha3.set_index('timestamp', inplace = True)
alpha3.head(10)
list = alpha3.index.tolist()
list[0:20]
alpha3[['open', 'close']].head(20).plot(figsize = (10,7))
plt.xticks(rotation = 45)
plt.show()
alpha3.iloc[:, 0:2].plot()
plt.show()
ts = TimeSeries(key = 'HK550L4D3IIB0IMZ', output_format='pandas')
print("THE REAL ESTATE STOCK MARKET EQR")
alpha4 = pd.read_csv(
    'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=MSFT&apikey=' + demo + '&datatype=csv')
alpha4.head()
alpha4.set_index('timestamp', inplace = True)
alpha4.head(10)
list = alpha4.index.tolist()
list[0:20]
alpha4[['open', 'close']].head(20).plot(figsize = (10,7))
plt.xticks(rotation = 45)
plt.show()
alpha4.iloc[:, 0:2].plot()
plt.show()
ts = TimeSeries(key = 'HK550L4D3IIB0IMZ', output_format='pandas')
print("GOLD METAL  STOCK MARKET TXG")
alpha4 = pd.read_csv(
    'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=MSFT&apikey=' + demo + '&datatype=csv')
alpha4.head()
alpha4.set_index('timestamp', inplace = True)
alpha4.head(10)
list = alpha4.index.tolist()
list[0:20]
alpha4[['open', 'close']].head(20).plot(figsize = (10,7))
plt.xticks(rotation = 45)
plt.show()
alpha4.iloc[:, 0:2].plot()
plt.show()
ts = TimeSeries(key = 'HK550L4D3IIB0IMZ', output_format='pandas')